name: ftpconnect_sample
description: A Flutter ftpconnect sample project.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path: any
  archive: any
  ftpconnect: any
